DOC: Migrate Read the Docs settings to file and switch from python 3.7 to 3.9
This should address the following error:

  exception: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl'
  module is compiled with OpenSSL 1.0.2n  7 Dec 2017.
  See: https://github.com/urllib3/urllib3/issues/2168