Fixed build error on VS2013
Problem: build error on Visual Studio 2013

    2>c:\d\slicersegmentmesher-win64rel\cleaver\src\lib\cleaver\Vertex.h(53): error C2039: 'int8_t' : is not a member of 'std'

Solution: int8_t is used instead of std::int8_t (and stdint.h is included). This is how it is done in all other places in Cleaver2, and it works well in Visual Studio 2013.