Improve readme and documentation (#123)
* DOC: Improve README adding Overview/Method/Documentation/Authors/Acknowledgment/Citing

* To be consistent with how the project is referenced, title
  is changed from "Cleaver2" to "Cleaver".

* Remove broken "travis" badge

* Remove explicit table of content. GitHub provide a built-in way
  for displaying it.
  See https://github.blog/changelog/2021-04-13-table-of-contents-support-in-markdown-files/

* Remove duplicated (and different) license. This should help reduce confusion.

* Instead of the mailing list, suggest the GitHub discussion board for
  asking question.

* The introduction of sections like Overview, Method, Documentation, Authors,
  Acknowledgment and "Citing Cleaver" is based on the README file available
  in pyvista/pyvista@7817dd9

Co-authored-by: Bane Sullivan <bane.sullivan@kitware.com>

* DOC: Remove empty & unused "Indices and tables" section

Since there are no python packagea or modules documented along side
Cleaver, there is no need to attempt generating or linking to the
associated pages.

> genindex, modindex, search
>
> These are used for the general index, the Python module index,
> and the search page, respectively.
>
> The general index is populated with entries from modules, all
> index-generating object descriptions, and from index directives.
>
> The Python module index contains one entry per py:module directive.
>
> The search page contains a form that uses the generated JSON search
> index and JavaScript to full-text search the generated documents for
> search words; it should work on every major browser that supports
> modern JavaScript.

See https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#special-names

* DOC: Improve "Authors" section

* DOC: Rename "Cleaver2" to "Cleaver" in docstrings and manual

* ENH: Rename "Cleaver2" to "Cleaver" in CLI and GUI applications

* ENH: Update obsolete documentation URL in GUI application About dialog

Update from

  https://sciinstitute.github.io/cleaver.pages/

to

  https://cleaver.readthedocs.io

* DOC: Fix documentation build warnings

docs/index.rst:30: WARNING: Title underline too short.
docs/manual.md:53: WARNING: image file not readable: ../_static/images/application.png
docs/build.md:7: WARNING: 'myst' cross-reference target not found: 'qt.io' [myst.xref_missing]
docs/specs.md:25: WARNING: 'myst' cross-reference target not found: 'build.html' [myst.xref_missing]

Also fix include of "_static/images/mesh.png"

* DOC: Update conf.py updating comments

* DOC: Ensure Copyright year reported in generated documentation is current

* DOC: Cleanup requirements.txt

- order alphabetically
- remove duplicates
- remove unused "lxml" dependency. This is most likely copied over from
  the Slicer configuration used as a reference.
- remove sphinx_markdown_tables that is conflicting with the table
  support integrated through the "furo" theme (e.g markdown tables were
  not centered)
- remove explicit listing of "docutils" and "pygment" already included
  through the "furo" theme.

* DOC: Update Cleaver bibliography

- Update "references.bib"
- Add text describing the list of publications

* DOC: Ensure Cleaver is referenced consistently

This fixes removes references likely introduced through copy/paste
from documentation associated with other tools.

* DOC: Convert index from reStructuredText to MyST Markdown

* STYLE: Update .gitignore to ensure only exclude top-level build directories

This ensures that files starting with "build_" and not ignored when
added to the docs folder.

* DOC: Remove "layout.html" template not supported by "furo" theme

From "furo" changelog:

> Generate an error page, for documents using layout.html from Sphinx’s basic theme.

See https://pradyunsg.me/furo/changelog/#beta22

* DOC: Re-organize documentation

- Add "About" document and simplify top-level README

- Add "Getting Started" and "API" documents

- Re-organize "Building" instruction and move ITK instructions into
  its own document.

- Manual
  * Rename title from "Using Cleaver" to "Manual"
  * Move list of cards known to not support Cleaver to "Getting Started / System Requirements"

- Introduce "sphinx-design" extension.
  See https://sphinx-design.readthedocs.io/en/furo-theme/get_started.html

* DOC: Improve ITK build instructions

* DOC: Simplify build instructions using Qt5_DIR and referencing Qt 5.15.2

* DOC: Update build instructions

* Set the BUILD_GUI and BUILD_GUI to ON
* Specify valid source and build directories based on $HOME or %HOMEPATH%
* Use CMake commannd line options -S and -B to avoid the explicit creation
  of the build directory.

* DOC: Migrate Read the Docs settings to file and switch from python 3.7 to 3.9

This should address the following error:

  exception: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl'
  module is compiled with OpenSSL 1.0.2n  7 Dec 2017.
  See: https://github.com/urllib3/urllib3/issues/2168

* correcting spelling and link

---------

Co-authored-by: Bane Sullivan <bane.sullivan@kitware.com>
Co-authored-by: jessdtate <jess@sci.utah.edu>